// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_simulation_error.proto

package sim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Errors in the simulator
type SimulatorError struct {
	// Unique code of the error for automatic handling on client side
	Code *string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	// Human readable description of the error
	Message              *string  `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimulatorError) Reset()         { *m = SimulatorError{} }
func (m *SimulatorError) String() string { return proto.CompactTextString(m) }
func (*SimulatorError) ProtoMessage()    {}
func (*SimulatorError) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0e1f90eb68206c2, []int{0}
}

func (m *SimulatorError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulatorError.Unmarshal(m, b)
}
func (m *SimulatorError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulatorError.Marshal(b, m, deterministic)
}
func (m *SimulatorError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulatorError.Merge(m, src)
}
func (m *SimulatorError) XXX_Size() int {
	return xxx_messageInfo_SimulatorError.Size(m)
}
func (m *SimulatorError) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulatorError.DiscardUnknown(m)
}

var xxx_messageInfo_SimulatorError proto.InternalMessageInfo

func (m *SimulatorError) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

func (m *SimulatorError) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SimulatorError)(nil), "SimulatorError")
}

func init() {
	proto.RegisterFile("ssl_simulation_error.proto", fileDescriptor_f0e1f90eb68206c2)
}

var fileDescriptor_f0e1f90eb68206c2 = []byte{
	// 144 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2a, 0x2e, 0xce, 0x89,
	0x2f, 0xce, 0xcc, 0x2d, 0xcd, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x8b, 0x4f, 0x2d, 0x2a, 0xca, 0x2f,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe3, 0xe2, 0x0b, 0x86, 0xc8, 0xe4, 0x17, 0xb9,
	0x82, 0xc4, 0x85, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x09, 0x26,
	0xb0, 0x30, 0x8c, 0xeb, 0x64, 0x11, 0x65, 0x96, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c,
	0x9f, 0xab, 0x1f, 0x94, 0x9f, 0x94, 0xef, 0x5c, 0x5a, 0xa0, 0x1b, 0x1c, 0xec, 0xa3, 0x5f, 0x5c,
	0x9c, 0xa3, 0x8b, 0xb0, 0x54, 0x17, 0x6c, 0x5d, 0x72, 0x7e, 0x8e, 0x7e, 0x41, 0x76, 0xba, 0x7e,
	0x71, 0x66, 0x2e, 0x20, 0x00, 0x00, 0xff, 0xff, 0xe1, 0x84, 0xf0, 0x56, 0x96, 0x00, 0x00, 0x00,
}
