// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_simulation_robot_control.proto

package sim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Full command for a single robot
type RobotCommand struct {
	// Id of the robot
	Id *uint32 `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	// Movement command
	MoveCommand *RobotMoveCommand `protobuf:"bytes,2,opt,name=move_command,json=moveCommand" json:"move_command,omitempty"`
	// Absolute (3 dimensional) kick speed [m/s]
	KickSpeed *float32 `protobuf:"fixed32,3,opt,name=kick_speed,json=kickSpeed" json:"kick_speed,omitempty"`
	// Kick angle [degree] (defaults to 0 degrees for a straight kick)
	KickAngle *float32 `protobuf:"fixed32,4,opt,name=kick_angle,json=kickAngle,def=0" json:"kick_angle,omitempty"`
	// Dribbler speed in rounds per minute [rpm]
	DribblerSpeed        *float32 `protobuf:"fixed32,5,opt,name=dribbler_speed,json=dribblerSpeed" json:"dribbler_speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotCommand) Reset()         { *m = RobotCommand{} }
func (m *RobotCommand) String() string { return proto.CompactTextString(m) }
func (*RobotCommand) ProtoMessage()    {}
func (*RobotCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_915614bed9207b5a, []int{0}
}

func (m *RobotCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotCommand.Unmarshal(m, b)
}
func (m *RobotCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotCommand.Marshal(b, m, deterministic)
}
func (m *RobotCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotCommand.Merge(m, src)
}
func (m *RobotCommand) XXX_Size() int {
	return xxx_messageInfo_RobotCommand.Size(m)
}
func (m *RobotCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RobotCommand proto.InternalMessageInfo

const Default_RobotCommand_KickAngle float32 = 0

func (m *RobotCommand) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RobotCommand) GetMoveCommand() *RobotMoveCommand {
	if m != nil {
		return m.MoveCommand
	}
	return nil
}

func (m *RobotCommand) GetKickSpeed() float32 {
	if m != nil && m.KickSpeed != nil {
		return *m.KickSpeed
	}
	return 0
}

func (m *RobotCommand) GetKickAngle() float32 {
	if m != nil && m.KickAngle != nil {
		return *m.KickAngle
	}
	return Default_RobotCommand_KickAngle
}

func (m *RobotCommand) GetDribblerSpeed() float32 {
	if m != nil && m.DribblerSpeed != nil {
		return *m.DribblerSpeed
	}
	return 0
}

// Wrapper for different kinds of movement commands
type RobotMoveCommand struct {
	// Types that are valid to be assigned to Command:
	//	*RobotMoveCommand_WheelVelocity
	//	*RobotMoveCommand_LocalVelocity
	//	*RobotMoveCommand_GlobalVelocity
	Command              isRobotMoveCommand_Command `protobuf_oneof:"command"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RobotMoveCommand) Reset()         { *m = RobotMoveCommand{} }
func (m *RobotMoveCommand) String() string { return proto.CompactTextString(m) }
func (*RobotMoveCommand) ProtoMessage()    {}
func (*RobotMoveCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_915614bed9207b5a, []int{1}
}

func (m *RobotMoveCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotMoveCommand.Unmarshal(m, b)
}
func (m *RobotMoveCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotMoveCommand.Marshal(b, m, deterministic)
}
func (m *RobotMoveCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotMoveCommand.Merge(m, src)
}
func (m *RobotMoveCommand) XXX_Size() int {
	return xxx_messageInfo_RobotMoveCommand.Size(m)
}
func (m *RobotMoveCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotMoveCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RobotMoveCommand proto.InternalMessageInfo

type isRobotMoveCommand_Command interface {
	isRobotMoveCommand_Command()
}

type RobotMoveCommand_WheelVelocity struct {
	WheelVelocity *MoveWheelVelocity `protobuf:"bytes,1,opt,name=wheel_velocity,json=wheelVelocity,oneof"`
}

type RobotMoveCommand_LocalVelocity struct {
	LocalVelocity *MoveLocalVelocity `protobuf:"bytes,2,opt,name=local_velocity,json=localVelocity,oneof"`
}

type RobotMoveCommand_GlobalVelocity struct {
	GlobalVelocity *MoveGlobalVelocity `protobuf:"bytes,3,opt,name=global_velocity,json=globalVelocity,oneof"`
}

func (*RobotMoveCommand_WheelVelocity) isRobotMoveCommand_Command() {}

func (*RobotMoveCommand_LocalVelocity) isRobotMoveCommand_Command() {}

func (*RobotMoveCommand_GlobalVelocity) isRobotMoveCommand_Command() {}

func (m *RobotMoveCommand) GetCommand() isRobotMoveCommand_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *RobotMoveCommand) GetWheelVelocity() *MoveWheelVelocity {
	if x, ok := m.GetCommand().(*RobotMoveCommand_WheelVelocity); ok {
		return x.WheelVelocity
	}
	return nil
}

func (m *RobotMoveCommand) GetLocalVelocity() *MoveLocalVelocity {
	if x, ok := m.GetCommand().(*RobotMoveCommand_LocalVelocity); ok {
		return x.LocalVelocity
	}
	return nil
}

func (m *RobotMoveCommand) GetGlobalVelocity() *MoveGlobalVelocity {
	if x, ok := m.GetCommand().(*RobotMoveCommand_GlobalVelocity); ok {
		return x.GlobalVelocity
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*RobotMoveCommand) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*RobotMoveCommand_WheelVelocity)(nil),
		(*RobotMoveCommand_LocalVelocity)(nil),
		(*RobotMoveCommand_GlobalVelocity)(nil),
	}
}

// Move robot with wheel velocities
type MoveWheelVelocity struct {
	// Velocity [m/s] of front right wheel
	FrontRight *float32 `protobuf:"fixed32,1,req,name=front_right,json=frontRight" json:"front_right,omitempty"`
	// Velocity [m/s] of back right wheel
	BackRight *float32 `protobuf:"fixed32,2,req,name=back_right,json=backRight" json:"back_right,omitempty"`
	// Velocity [m/s] of back left wheel
	BackLeft *float32 `protobuf:"fixed32,3,req,name=back_left,json=backLeft" json:"back_left,omitempty"`
	// Velocity [m/s] of front left wheel
	FrontLeft            *float32 `protobuf:"fixed32,4,req,name=front_left,json=frontLeft" json:"front_left,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveWheelVelocity) Reset()         { *m = MoveWheelVelocity{} }
func (m *MoveWheelVelocity) String() string { return proto.CompactTextString(m) }
func (*MoveWheelVelocity) ProtoMessage()    {}
func (*MoveWheelVelocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_915614bed9207b5a, []int{2}
}

func (m *MoveWheelVelocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveWheelVelocity.Unmarshal(m, b)
}
func (m *MoveWheelVelocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveWheelVelocity.Marshal(b, m, deterministic)
}
func (m *MoveWheelVelocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveWheelVelocity.Merge(m, src)
}
func (m *MoveWheelVelocity) XXX_Size() int {
	return xxx_messageInfo_MoveWheelVelocity.Size(m)
}
func (m *MoveWheelVelocity) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveWheelVelocity.DiscardUnknown(m)
}

var xxx_messageInfo_MoveWheelVelocity proto.InternalMessageInfo

func (m *MoveWheelVelocity) GetFrontRight() float32 {
	if m != nil && m.FrontRight != nil {
		return *m.FrontRight
	}
	return 0
}

func (m *MoveWheelVelocity) GetBackRight() float32 {
	if m != nil && m.BackRight != nil {
		return *m.BackRight
	}
	return 0
}

func (m *MoveWheelVelocity) GetBackLeft() float32 {
	if m != nil && m.BackLeft != nil {
		return *m.BackLeft
	}
	return 0
}

func (m *MoveWheelVelocity) GetFrontLeft() float32 {
	if m != nil && m.FrontLeft != nil {
		return *m.FrontLeft
	}
	return 0
}

// Move robot with local velocity
type MoveLocalVelocity struct {
	// Velocity forward [m/s] (towards the dribbler)
	Forward *float32 `protobuf:"fixed32,1,req,name=forward" json:"forward,omitempty"`
	// Velocity to the left [m/s]
	Left *float32 `protobuf:"fixed32,2,req,name=left" json:"left,omitempty"`
	// Angular velocity counter-clockwise [rad/s]
	Angular              *float32 `protobuf:"fixed32,3,req,name=angular" json:"angular,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveLocalVelocity) Reset()         { *m = MoveLocalVelocity{} }
func (m *MoveLocalVelocity) String() string { return proto.CompactTextString(m) }
func (*MoveLocalVelocity) ProtoMessage()    {}
func (*MoveLocalVelocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_915614bed9207b5a, []int{3}
}

func (m *MoveLocalVelocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveLocalVelocity.Unmarshal(m, b)
}
func (m *MoveLocalVelocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveLocalVelocity.Marshal(b, m, deterministic)
}
func (m *MoveLocalVelocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveLocalVelocity.Merge(m, src)
}
func (m *MoveLocalVelocity) XXX_Size() int {
	return xxx_messageInfo_MoveLocalVelocity.Size(m)
}
func (m *MoveLocalVelocity) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveLocalVelocity.DiscardUnknown(m)
}

var xxx_messageInfo_MoveLocalVelocity proto.InternalMessageInfo

func (m *MoveLocalVelocity) GetForward() float32 {
	if m != nil && m.Forward != nil {
		return *m.Forward
	}
	return 0
}

func (m *MoveLocalVelocity) GetLeft() float32 {
	if m != nil && m.Left != nil {
		return *m.Left
	}
	return 0
}

func (m *MoveLocalVelocity) GetAngular() float32 {
	if m != nil && m.Angular != nil {
		return *m.Angular
	}
	return 0
}

// Move robot with global velocity
type MoveGlobalVelocity struct {
	// Velocity on x-axis of the field [m/s]
	X *float32 `protobuf:"fixed32,1,req,name=x" json:"x,omitempty"`
	// Velocity on y-axis of the field [m/s]
	Y *float32 `protobuf:"fixed32,2,req,name=y" json:"y,omitempty"`
	// Angular velocity counter-clockwise [rad/s]
	Angular              *float32 `protobuf:"fixed32,3,req,name=angular" json:"angular,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoveGlobalVelocity) Reset()         { *m = MoveGlobalVelocity{} }
func (m *MoveGlobalVelocity) String() string { return proto.CompactTextString(m) }
func (*MoveGlobalVelocity) ProtoMessage()    {}
func (*MoveGlobalVelocity) Descriptor() ([]byte, []int) {
	return fileDescriptor_915614bed9207b5a, []int{4}
}

func (m *MoveGlobalVelocity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoveGlobalVelocity.Unmarshal(m, b)
}
func (m *MoveGlobalVelocity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoveGlobalVelocity.Marshal(b, m, deterministic)
}
func (m *MoveGlobalVelocity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoveGlobalVelocity.Merge(m, src)
}
func (m *MoveGlobalVelocity) XXX_Size() int {
	return xxx_messageInfo_MoveGlobalVelocity.Size(m)
}
func (m *MoveGlobalVelocity) XXX_DiscardUnknown() {
	xxx_messageInfo_MoveGlobalVelocity.DiscardUnknown(m)
}

var xxx_messageInfo_MoveGlobalVelocity proto.InternalMessageInfo

func (m *MoveGlobalVelocity) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MoveGlobalVelocity) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *MoveGlobalVelocity) GetAngular() float32 {
	if m != nil && m.Angular != nil {
		return *m.Angular
	}
	return 0
}

// Command from the connected client to the simulator
type RobotControl struct {
	// Control the robots
	RobotCommands        []*RobotCommand `protobuf:"bytes,1,rep,name=robot_commands,json=robotCommands" json:"robot_commands,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RobotControl) Reset()         { *m = RobotControl{} }
func (m *RobotControl) String() string { return proto.CompactTextString(m) }
func (*RobotControl) ProtoMessage()    {}
func (*RobotControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_915614bed9207b5a, []int{5}
}

func (m *RobotControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotControl.Unmarshal(m, b)
}
func (m *RobotControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotControl.Marshal(b, m, deterministic)
}
func (m *RobotControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotControl.Merge(m, src)
}
func (m *RobotControl) XXX_Size() int {
	return xxx_messageInfo_RobotControl.Size(m)
}
func (m *RobotControl) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotControl.DiscardUnknown(m)
}

var xxx_messageInfo_RobotControl proto.InternalMessageInfo

func (m *RobotControl) GetRobotCommands() []*RobotCommand {
	if m != nil {
		return m.RobotCommands
	}
	return nil
}

func init() {
	proto.RegisterType((*RobotCommand)(nil), "RobotCommand")
	proto.RegisterType((*RobotMoveCommand)(nil), "RobotMoveCommand")
	proto.RegisterType((*MoveWheelVelocity)(nil), "MoveWheelVelocity")
	proto.RegisterType((*MoveLocalVelocity)(nil), "MoveLocalVelocity")
	proto.RegisterType((*MoveGlobalVelocity)(nil), "MoveGlobalVelocity")
	proto.RegisterType((*RobotControl)(nil), "RobotControl")
}

func init() {
	proto.RegisterFile("ssl_simulation_robot_control.proto", fileDescriptor_915614bed9207b5a)
}

var fileDescriptor_915614bed9207b5a = []byte{
	// 479 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0x5f, 0x8b, 0xd3, 0x4c,
	0x14, 0xc6, 0xdf, 0x49, 0xfb, 0xb2, 0xf6, 0xb4, 0x89, 0xee, 0x78, 0x13, 0x10, 0x31, 0x04, 0x84,
	0xde, 0x34, 0x95, 0x65, 0x11, 0x51, 0x10, 0xdc, 0x15, 0x14, 0xa9, 0x37, 0x29, 0x28, 0xe8, 0x45,
	0xc8, 0x9f, 0x69, 0x3a, 0x74, 0x92, 0x29, 0x93, 0x69, 0xbb, 0xfd, 0x14, 0x7e, 0x21, 0xbf, 0x87,
	0x5f, 0x47, 0xe6, 0x64, 0xea, 0xce, 0xba, 0xe0, 0x5d, 0xcf, 0xf3, 0x3b, 0xcf, 0xd3, 0xc3, 0xc9,
	0x19, 0x88, 0xbb, 0x4e, 0x64, 0x1d, 0x6f, 0x76, 0x22, 0xd7, 0x5c, 0xb6, 0x99, 0x92, 0x85, 0xd4,
	0x59, 0x29, 0x5b, 0xad, 0xa4, 0x48, 0xb6, 0x4a, 0x6a, 0x19, 0xff, 0x24, 0x30, 0x49, 0x8d, 0x7e,
	0x2d, 0x9b, 0x26, 0x6f, 0x2b, 0x1a, 0x80, 0xc7, 0xab, 0x90, 0x44, 0xde, 0xd4, 0x4f, 0x3d, 0x5e,
	0xd1, 0x4b, 0x98, 0x34, 0x72, 0xcf, 0xb2, 0xb2, 0xe7, 0xa1, 0x17, 0x91, 0xe9, 0xf8, 0xe2, 0x3c,
	0x41, 0xd3, 0x67, 0xb9, 0x67, 0xd6, 0x98, 0x8e, 0x9b, 0xdb, 0x82, 0x3e, 0x05, 0xd8, 0xf0, 0x72,
	0x93, 0x75, 0x5b, 0xc6, 0xaa, 0x70, 0x10, 0x91, 0xa9, 0x97, 0x8e, 0x8c, 0xb2, 0x34, 0x02, 0x8d,
	0x2c, 0xce, 0xdb, 0x5a, 0xb0, 0x70, 0x68, 0xf0, 0x6b, 0xf2, 0xa2, 0xef, 0x78, 0x67, 0x34, 0xfa,
	0x1c, 0x82, 0x4a, 0xf1, 0xa2, 0x10, 0x4c, 0xd9, 0x90, 0xff, 0x31, 0xc4, 0x3f, 0xa9, 0x18, 0x14,
	0xff, 0x22, 0xf0, 0xe8, 0xef, 0x49, 0xe8, 0x1b, 0x08, 0x0e, 0x6b, 0xc6, 0x44, 0xb6, 0x67, 0x42,
	0x96, 0x5c, 0x1f, 0x43, 0x82, 0x43, 0xd3, 0xc4, 0x74, 0x7d, 0x35, 0xe8, 0x8b, 0x25, 0x1f, 0xff,
	0x4b, 0xfd, 0x83, 0x2b, 0x18, 0xb3, 0x90, 0x65, 0xee, 0x98, 0x3d, 0xc7, 0xbc, 0x30, 0xc8, 0x35,
	0x0b, 0x57, 0xa0, 0x6f, 0xe1, 0x61, 0x2d, 0x64, 0xe1, 0xba, 0x07, 0xe8, 0x7e, 0x8c, 0xee, 0x0f,
	0xc8, 0x1c, 0x7b, 0x50, 0xdf, 0x51, 0xae, 0x46, 0x70, 0x66, 0xf7, 0x1c, 0xff, 0x20, 0x70, 0x7e,
	0x6f, 0x5c, 0xfa, 0x0c, 0xc6, 0x2b, 0x25, 0x5b, 0x9d, 0x29, 0x5e, 0xaf, 0x35, 0x7e, 0x26, 0x2f,
	0x05, 0x94, 0x52, 0xa3, 0x98, 0xc5, 0x17, 0x79, 0xb9, 0xb1, 0xdc, 0x43, 0x3e, 0x32, 0x4a, 0x8f,
	0x9f, 0x00, 0x16, 0x99, 0x60, 0x2b, 0x1d, 0x0e, 0x90, 0x3e, 0x30, 0xc2, 0x82, 0xad, 0xd0, 0xdb,
	0x87, 0x23, 0x1d, 0xf6, 0x5e, 0x54, 0x0c, 0x8e, 0xbf, 0xf7, 0x03, 0xdd, 0x59, 0x01, 0x0d, 0xe1,
	0x6c, 0x25, 0xd5, 0x21, 0x57, 0x95, 0x1d, 0xe6, 0x54, 0x52, 0x0a, 0x43, 0xcc, 0xe9, 0x67, 0xc0,
	0xdf, 0xa6, 0x3b, 0x6f, 0xeb, 0x9d, 0xc8, 0x95, 0xfd, 0xf3, 0x53, 0x19, 0x7f, 0x02, 0x7a, 0x7f,
	0x43, 0x74, 0x02, 0xe4, 0xc6, 0xe6, 0x92, 0x1b, 0x53, 0x1d, 0x6d, 0x1c, 0x39, 0xfe, 0x23, 0xeb,
	0xfd, 0x9f, 0x93, 0xc6, 0x4b, 0xa7, 0x97, 0x10, 0x9c, 0x4e, 0x1f, 0x77, 0xdb, 0x85, 0x24, 0x1a,
	0x4c, 0xc7, 0x17, 0x7e, 0xe2, 0x5e, 0x7e, 0xea, 0x2b, 0xa7, 0xea, 0xae, 0x5e, 0x7d, 0x7b, 0x59,
	0x73, 0xbd, 0xde, 0x15, 0x49, 0x29, 0x9b, 0xb9, 0xe9, 0xbc, 0xde, 0x6d, 0x67, 0xcb, 0xe5, 0x62,
	0xde, 0x75, 0x62, 0x76, 0xfb, 0xac, 0x66, 0xf8, 0x90, 0x4a, 0x29, 0xe6, 0xdb, 0x4d, 0x3d, 0xef,
	0x78, 0xf3, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x3e, 0x72, 0xb0, 0x78, 0x03, 0x00, 0x00,
}
