// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_simulation_control.proto

package sim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Teleport the ball to a new location and optionally set it to some velocity
type TeleportBall struct {
	// x-coordinate [m]
	X *float32 `protobuf:"fixed32,1,opt,name=x" json:"x,omitempty"`
	// y-coordinate [m]
	Y *float32 `protobuf:"fixed32,2,opt,name=y" json:"y,omitempty"`
	// z-coordinate (height) [m]
	Z *float32 `protobuf:"fixed32,3,opt,name=z" json:"z,omitempty"`
	// Velocity in x-direction [m/s]
	Vx *float32 `protobuf:"fixed32,4,opt,name=vx" json:"vx,omitempty"`
	// Velocity in y-direction [m/s]
	Vy *float32 `protobuf:"fixed32,5,opt,name=vy" json:"vy,omitempty"`
	// Velocity in z-direction [m/s]
	Vz *float32 `protobuf:"fixed32,6,opt,name=vz" json:"vz,omitempty"`
	// Teleport the ball safely to the target, for example by
	// moving robots out of the way in case of collision and set speed of robots close-by to zero
	TeleportSafely *bool `protobuf:"varint,7,opt,name=teleport_safely,json=teleportSafely,def=0" json:"teleport_safely,omitempty"`
	// Adapt the angular ball velocity such that the ball is rolling
	Roll                 *bool    `protobuf:"varint,8,opt,name=roll,def=0" json:"roll,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeleportBall) Reset()         { *m = TeleportBall{} }
func (m *TeleportBall) String() string { return proto.CompactTextString(m) }
func (*TeleportBall) ProtoMessage()    {}
func (*TeleportBall) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6a496d4d405512, []int{0}
}

func (m *TeleportBall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeleportBall.Unmarshal(m, b)
}
func (m *TeleportBall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeleportBall.Marshal(b, m, deterministic)
}
func (m *TeleportBall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeleportBall.Merge(m, src)
}
func (m *TeleportBall) XXX_Size() int {
	return xxx_messageInfo_TeleportBall.Size(m)
}
func (m *TeleportBall) XXX_DiscardUnknown() {
	xxx_messageInfo_TeleportBall.DiscardUnknown(m)
}

var xxx_messageInfo_TeleportBall proto.InternalMessageInfo

const Default_TeleportBall_TeleportSafely bool = false
const Default_TeleportBall_Roll bool = false

func (m *TeleportBall) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *TeleportBall) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *TeleportBall) GetZ() float32 {
	if m != nil && m.Z != nil {
		return *m.Z
	}
	return 0
}

func (m *TeleportBall) GetVx() float32 {
	if m != nil && m.Vx != nil {
		return *m.Vx
	}
	return 0
}

func (m *TeleportBall) GetVy() float32 {
	if m != nil && m.Vy != nil {
		return *m.Vy
	}
	return 0
}

func (m *TeleportBall) GetVz() float32 {
	if m != nil && m.Vz != nil {
		return *m.Vz
	}
	return 0
}

func (m *TeleportBall) GetTeleportSafely() bool {
	if m != nil && m.TeleportSafely != nil {
		return *m.TeleportSafely
	}
	return Default_TeleportBall_TeleportSafely
}

func (m *TeleportBall) GetRoll() bool {
	if m != nil && m.Roll != nil {
		return *m.Roll
	}
	return Default_TeleportBall_Roll
}

// Teleport a robot to some location and give it a velocity
type TeleportRobot struct {
	// Robot id to teleport
	Id *RobotId `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	// x-coordinate [m]
	X *float32 `protobuf:"fixed32,2,opt,name=x" json:"x,omitempty"`
	// y-coordinate [m]
	Y *float32 `protobuf:"fixed32,3,opt,name=y" json:"y,omitempty"`
	// Orientation [rad], measured from the x-axis counter-clockwise
	Orientation *float32 `protobuf:"fixed32,4,opt,name=orientation" json:"orientation,omitempty"`
	// Global velocity [m/s] towards x-axis
	VX *float32 `protobuf:"fixed32,5,opt,name=v_x,json=vX" json:"v_x,omitempty"`
	// Global velocity [m/s] towards y-axis
	VY *float32 `protobuf:"fixed32,6,opt,name=v_y,json=vY" json:"v_y,omitempty"`
	// Angular velocity [rad/s]
	VAngular             *float32 `protobuf:"fixed32,7,opt,name=v_angular,json=vAngular" json:"v_angular,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeleportRobot) Reset()         { *m = TeleportRobot{} }
func (m *TeleportRobot) String() string { return proto.CompactTextString(m) }
func (*TeleportRobot) ProtoMessage()    {}
func (*TeleportRobot) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6a496d4d405512, []int{1}
}

func (m *TeleportRobot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeleportRobot.Unmarshal(m, b)
}
func (m *TeleportRobot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeleportRobot.Marshal(b, m, deterministic)
}
func (m *TeleportRobot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeleportRobot.Merge(m, src)
}
func (m *TeleportRobot) XXX_Size() int {
	return xxx_messageInfo_TeleportRobot.Size(m)
}
func (m *TeleportRobot) XXX_DiscardUnknown() {
	xxx_messageInfo_TeleportRobot.DiscardUnknown(m)
}

var xxx_messageInfo_TeleportRobot proto.InternalMessageInfo

func (m *TeleportRobot) GetId() *RobotId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TeleportRobot) GetX() float32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *TeleportRobot) GetY() float32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *TeleportRobot) GetOrientation() float32 {
	if m != nil && m.Orientation != nil {
		return *m.Orientation
	}
	return 0
}

func (m *TeleportRobot) GetVX() float32 {
	if m != nil && m.VX != nil {
		return *m.VX
	}
	return 0
}

func (m *TeleportRobot) GetVY() float32 {
	if m != nil && m.VY != nil {
		return *m.VY
	}
	return 0
}

func (m *TeleportRobot) GetVAngular() float32 {
	if m != nil && m.VAngular != nil {
		return *m.VAngular
	}
	return 0
}

// Control the simulation
type SimulatorControl struct {
	// Teleport the ball
	TeleportBall *TeleportBall `protobuf:"bytes,1,opt,name=teleport_ball,json=teleportBall" json:"teleport_ball,omitempty"`
	// Teleport robots
	TeleportRobot []*TeleportRobot `protobuf:"bytes,2,rep,name=teleport_robot,json=teleportRobot" json:"teleport_robot,omitempty"`
	// Change the simulation speed
	SimulationSpeed      *float32 `protobuf:"fixed32,3,opt,name=simulation_speed,json=simulationSpeed" json:"simulation_speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimulatorControl) Reset()         { *m = SimulatorControl{} }
func (m *SimulatorControl) String() string { return proto.CompactTextString(m) }
func (*SimulatorControl) ProtoMessage()    {}
func (*SimulatorControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6a496d4d405512, []int{2}
}

func (m *SimulatorControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulatorControl.Unmarshal(m, b)
}
func (m *SimulatorControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulatorControl.Marshal(b, m, deterministic)
}
func (m *SimulatorControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulatorControl.Merge(m, src)
}
func (m *SimulatorControl) XXX_Size() int {
	return xxx_messageInfo_SimulatorControl.Size(m)
}
func (m *SimulatorControl) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulatorControl.DiscardUnknown(m)
}

var xxx_messageInfo_SimulatorControl proto.InternalMessageInfo

func (m *SimulatorControl) GetTeleportBall() *TeleportBall {
	if m != nil {
		return m.TeleportBall
	}
	return nil
}

func (m *SimulatorControl) GetTeleportRobot() []*TeleportRobot {
	if m != nil {
		return m.TeleportRobot
	}
	return nil
}

func (m *SimulatorControl) GetSimulationSpeed() float32 {
	if m != nil && m.SimulationSpeed != nil {
		return *m.SimulationSpeed
	}
	return 0
}

// Command from the connected client to the simulator
type SimulatorCommand struct {
	// Control the simulation
	Control *SimulatorControl `protobuf:"bytes,1,opt,name=control" json:"control,omitempty"`
	// Configure the simulation
	Config               *SimulatorConfig `protobuf:"bytes,2,opt,name=config" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SimulatorCommand) Reset()         { *m = SimulatorCommand{} }
func (m *SimulatorCommand) String() string { return proto.CompactTextString(m) }
func (*SimulatorCommand) ProtoMessage()    {}
func (*SimulatorCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6a496d4d405512, []int{3}
}

func (m *SimulatorCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulatorCommand.Unmarshal(m, b)
}
func (m *SimulatorCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulatorCommand.Marshal(b, m, deterministic)
}
func (m *SimulatorCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulatorCommand.Merge(m, src)
}
func (m *SimulatorCommand) XXX_Size() int {
	return xxx_messageInfo_SimulatorCommand.Size(m)
}
func (m *SimulatorCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulatorCommand.DiscardUnknown(m)
}

var xxx_messageInfo_SimulatorCommand proto.InternalMessageInfo

func (m *SimulatorCommand) GetControl() *SimulatorControl {
	if m != nil {
		return m.Control
	}
	return nil
}

func (m *SimulatorCommand) GetConfig() *SimulatorConfig {
	if m != nil {
		return m.Config
	}
	return nil
}

// Response of the simulator to the connected client
type SimulatorResponse struct {
	// List of errors, like using unsupported features
	Errors               []*SimulatorError `protobuf:"bytes,1,rep,name=errors" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SimulatorResponse) Reset()         { *m = SimulatorResponse{} }
func (m *SimulatorResponse) String() string { return proto.CompactTextString(m) }
func (*SimulatorResponse) ProtoMessage()    {}
func (*SimulatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7c6a496d4d405512, []int{4}
}

func (m *SimulatorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SimulatorResponse.Unmarshal(m, b)
}
func (m *SimulatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SimulatorResponse.Marshal(b, m, deterministic)
}
func (m *SimulatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimulatorResponse.Merge(m, src)
}
func (m *SimulatorResponse) XXX_Size() int {
	return xxx_messageInfo_SimulatorResponse.Size(m)
}
func (m *SimulatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimulatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimulatorResponse proto.InternalMessageInfo

func (m *SimulatorResponse) GetErrors() []*SimulatorError {
	if m != nil {
		return m.Errors
	}
	return nil
}

func init() {
	proto.RegisterType((*TeleportBall)(nil), "TeleportBall")
	proto.RegisterType((*TeleportRobot)(nil), "TeleportRobot")
	proto.RegisterType((*SimulatorControl)(nil), "SimulatorControl")
	proto.RegisterType((*SimulatorCommand)(nil), "SimulatorCommand")
	proto.RegisterType((*SimulatorResponse)(nil), "SimulatorResponse")
}

func init() {
	proto.RegisterFile("ssl_simulation_control.proto", fileDescriptor_7c6a496d4d405512)
}

var fileDescriptor_7c6a496d4d405512 = []byte{
	// 472 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x4f, 0x8f, 0xd3, 0x3c,
	0x18, 0xc4, 0x65, 0x77, 0xb7, 0xdb, 0xd7, 0xfd, 0xbb, 0x7e, 0x2f, 0x66, 0x97, 0x43, 0xd5, 0x0b,
	0x45, 0xa8, 0xa9, 0x14, 0x09, 0x84, 0x10, 0x17, 0x76, 0xc5, 0x01, 0x89, 0x93, 0xc3, 0x01, 0xb8,
	0x44, 0x69, 0xe2, 0x06, 0x0b, 0x27, 0x8e, 0xec, 0x34, 0x4a, 0xfa, 0x81, 0x10, 0x77, 0xbe, 0x20,
	0x8a, 0xed, 0xa6, 0xe9, 0x72, 0x9c, 0x19, 0x3b, 0xf1, 0x6f, 0x9e, 0x07, 0x3d, 0xd7, 0x5a, 0x84,
	0x9a, 0x67, 0x07, 0x11, 0x95, 0x5c, 0xe6, 0x61, 0x2c, 0xf3, 0x52, 0x49, 0xe1, 0x15, 0x4a, 0x96,
	0xf2, 0xee, 0xff, 0x36, 0x4d, 0xe3, 0x30, 0x96, 0x59, 0x26, 0x73, 0x67, 0xde, 0xff, 0x7b, 0x65,
	0xcf, 0x53, 0x17, 0xde, 0x3d, 0x09, 0x99, 0x52, 0x52, 0xd9, 0x6c, 0xf5, 0x07, 0xa0, 0xc9, 0x17,
	0x26, 0x58, 0x21, 0x55, 0xf9, 0x10, 0x09, 0x81, 0x27, 0x08, 0xd4, 0x04, 0x2c, 0xc1, 0x1a, 0x52,
	0x50, 0xb7, 0xaa, 0x21, 0xd0, 0xaa, 0xa6, 0x55, 0x47, 0x32, 0xb0, 0xea, 0x88, 0x67, 0x08, 0x56,
	0x35, 0xb9, 0x32, 0x12, 0x56, 0xb5, 0xd1, 0x0d, 0xb9, 0x76, 0xba, 0x31, 0xfa, 0x48, 0x86, 0x4e,
	0x1f, 0xb1, 0x87, 0xe6, 0xa5, 0xfb, 0x53, 0xa8, 0xa3, 0x3d, 0x13, 0x0d, 0xb9, 0x59, 0x82, 0xf5,
	0xe8, 0xdd, 0xf5, 0x3e, 0x12, 0x9a, 0xd1, 0xd9, 0x29, 0x0d, 0x4c, 0x88, 0x9f, 0xa1, 0x2b, 0x25,
	0x85, 0x20, 0xa3, 0xfe, 0x21, 0x63, 0xad, 0x7e, 0x01, 0x34, 0x3d, 0xbd, 0x9a, 0xca, 0x9d, 0x2c,
	0x31, 0x41, 0x90, 0x27, 0x04, 0x2c, 0xe1, 0x7a, 0xec, 0x8f, 0x3c, 0xe3, 0x7d, 0x4a, 0x28, 0xe4,
	0x89, 0x05, 0x82, 0x17, 0x40, 0x83, 0x13, 0xd0, 0x12, 0x8d, 0xa5, 0xe2, 0x2c, 0x2f, 0x4d, 0x31,
	0x8e, 0xa5, 0x6f, 0xe1, 0x39, 0x1a, 0x54, 0x61, 0xdd, 0x51, 0x7d, 0xb5, 0x46, 0xd3, 0x61, 0x7d,
	0xc3, 0xf7, 0xe8, 0xbf, 0x2a, 0x8c, 0xf2, 0xf4, 0x20, 0x22, 0x65, 0x80, 0x20, 0x1d, 0x55, 0x1f,
	0xac, 0x5e, 0xfd, 0x06, 0x68, 0x11, 0xd8, 0xe6, 0xa5, 0x7a, 0xb4, 0x73, 0xc4, 0x3e, 0x9a, 0x76,
	0x45, 0xec, 0x22, 0x21, 0x4c, 0xdd, 0x63, 0x7f, 0xea, 0xf5, 0x07, 0x41, 0x27, 0x65, 0x7f, 0x2c,
	0xaf, 0x51, 0x57, 0x4f, 0xa8, 0x5a, 0x3a, 0x02, 0x97, 0x83, 0xf5, 0xd8, 0x9f, 0x79, 0x17, 0x3d,
	0xd0, 0xee, 0xcb, 0xb6, 0x96, 0x97, 0x68, 0xd1, 0x1b, 0xbc, 0x2e, 0x18, 0x4b, 0x1c, 0xfd, 0xfc,
	0xec, 0x07, 0xad, 0xbd, 0xe2, 0x17, 0x2f, 0xcd, 0xb2, 0x28, 0x4f, 0xf0, 0x2b, 0x74, 0xe3, 0x96,
	0xcf, 0xbd, 0xf1, 0xd6, 0x7b, 0x4a, 0x43, 0x4f, 0x27, 0xf0, 0x1a, 0x0d, 0xed, 0xda, 0x99, 0xb6,
	0xc7, 0xfe, 0xe2, 0xe2, 0xec, 0x9e, 0xa7, 0xd4, 0xe5, 0xab, 0xf7, 0xe8, 0xb6, 0x8b, 0x28, 0xd3,
	0x85, 0xcc, 0x35, 0xc3, 0x2f, 0xd0, 0xd0, 0x2c, 0xa6, 0x26, 0xc0, 0x90, 0xcd, 0xcf, 0xd7, 0x3f,
	0xb6, 0x3e, 0x75, 0xf1, 0xc3, 0xdb, 0xef, 0x6f, 0x52, 0x5e, 0xfe, 0x38, 0xec, 0xbc, 0x58, 0x66,
	0xdb, 0x96, 0xf3, 0xf1, 0x50, 0x6c, 0x82, 0xe0, 0xf3, 0x56, 0x6b, 0xb1, 0x39, 0x63, 0x6d, 0xcc,
	0x86, 0xc7, 0x52, 0x6c, 0x8b, 0x9f, 0xe9, 0x56, 0xf3, 0xec, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa7, 0x41, 0x1b, 0x48, 0x59, 0x03, 0x00, 0x00,
}
