// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ssl_gc_common.proto

package sim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Team is either blue or yellow
type Team int32

const (
	// team not set
	Team_UNKNOWN Team = 0
	// yellow team
	Team_YELLOW Team = 1
	// blue team
	Team_BLUE Team = 2
)

var Team_name = map[int32]string{
	0: "UNKNOWN",
	1: "YELLOW",
	2: "BLUE",
}

var Team_value = map[string]int32{
	"UNKNOWN": 0,
	"YELLOW":  1,
	"BLUE":    2,
}

func (x Team) Enum() *Team {
	p := new(Team)
	*p = x
	return p
}

func (x Team) String() string {
	return proto.EnumName(Team_name, int32(x))
}

func (x *Team) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Team_value, data, "Team")
	if err != nil {
		return err
	}
	*x = Team(value)
	return nil
}

func (Team) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1df1d8f3f755967a, []int{0}
}

// Division denotes the current division, which influences some rules
type Division int32

const (
	Division_DIV_UNKNOWN Division = 0
	Division_DIV_A       Division = 1
	Division_DIV_B       Division = 2
)

var Division_name = map[int32]string{
	0: "DIV_UNKNOWN",
	1: "DIV_A",
	2: "DIV_B",
}

var Division_value = map[string]int32{
	"DIV_UNKNOWN": 0,
	"DIV_A":       1,
	"DIV_B":       2,
}

func (x Division) Enum() *Division {
	p := new(Division)
	*p = x
	return p
}

func (x Division) String() string {
	return proto.EnumName(Division_name, int32(x))
}

func (x *Division) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Division_value, data, "Division")
	if err != nil {
		return err
	}
	*x = Division(value)
	return nil
}

func (Division) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1df1d8f3f755967a, []int{1}
}

// RobotId is the combination of a team and a robot id
type RobotId struct {
	// the robot number
	Id *uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	// the team that the robot belongs to
	Team                 *Team    `protobuf:"varint,2,opt,name=team,enum=Team" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RobotId) Reset()         { *m = RobotId{} }
func (m *RobotId) String() string { return proto.CompactTextString(m) }
func (*RobotId) ProtoMessage()    {}
func (*RobotId) Descriptor() ([]byte, []int) {
	return fileDescriptor_1df1d8f3f755967a, []int{0}
}

func (m *RobotId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RobotId.Unmarshal(m, b)
}
func (m *RobotId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RobotId.Marshal(b, m, deterministic)
}
func (m *RobotId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RobotId.Merge(m, src)
}
func (m *RobotId) XXX_Size() int {
	return xxx_messageInfo_RobotId.Size(m)
}
func (m *RobotId) XXX_DiscardUnknown() {
	xxx_messageInfo_RobotId.DiscardUnknown(m)
}

var xxx_messageInfo_RobotId proto.InternalMessageInfo

func (m *RobotId) GetId() uint32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RobotId) GetTeam() Team {
	if m != nil && m.Team != nil {
		return *m.Team
	}
	return Team_UNKNOWN
}

func init() {
	proto.RegisterEnum("Team", Team_name, Team_value)
	proto.RegisterEnum("Division", Division_name, Division_value)
	proto.RegisterType((*RobotId)(nil), "RobotId")
}

func init() {
	proto.RegisterFile("ssl_gc_common.proto", fileDescriptor_1df1d8f3f755967a)
}

var fileDescriptor_1df1d8f3f755967a = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8f, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x4d, 0xe8, 0xdc, 0xfc, 0x86, 0x33, 0xc4, 0xcb, 0xbc, 0x0d, 0x4f, 0x73, 0xd0, 0x16,
	0x45, 0xc4, 0xab, 0x75, 0x3b, 0x0c, 0x43, 0x07, 0x9d, 0x73, 0xe8, 0xa5, 0x74, 0xe9, 0xa8, 0x1f,
	0x26, 0xfd, 0x8a, 0x49, 0xfd, 0xfb, 0xa5, 0x05, 0xf1, 0xf6, 0xde, 0x0f, 0x1e, 0xbc, 0x1f, 0x5c,
	0x3a, 0x67, 0xf2, 0x4a, 0xe7, 0x9a, 0xac, 0xa5, 0x3a, 0x6a, 0xbe, 0xc9, 0xd3, 0xf5, 0x3d, 0x0c,
	0x33, 0x3a, 0x90, 0x5f, 0x97, 0x72, 0x02, 0x1c, 0xcb, 0x29, 0x9b, 0xb1, 0xf9, 0x79, 0xc6, 0xb1,
	0x94, 0x57, 0x10, 0xf8, 0x63, 0x61, 0xa7, 0x7c, 0xc6, 0xe6, 0x93, 0xbb, 0x41, 0xf4, 0x7a, 0x2c,
	0x6c, 0xd6, 0xa3, 0xc5, 0x0d, 0x04, 0x5d, 0x93, 0x63, 0x18, 0xee, 0xd2, 0x97, 0x74, 0xb3, 0x4f,
	0xc5, 0x89, 0x04, 0x38, 0x7d, 0x5f, 0x29, 0xb5, 0xd9, 0x0b, 0x26, 0x47, 0x10, 0x24, 0x6a, 0xb7,
	0x12, 0x7c, 0x71, 0x0b, 0xa3, 0x25, 0xfe, 0xa0, 0x43, 0xaa, 0xe5, 0x05, 0x8c, 0x97, 0xeb, 0xb7,
	0xfc, 0x7f, 0x72, 0x06, 0x83, 0x0e, 0x3c, 0x09, 0xf6, 0x17, 0x13, 0xc1, 0x93, 0xc7, 0x8f, 0x87,
	0x0a, 0xfd, 0x67, 0x7b, 0x88, 0x34, 0xd9, 0xb8, 0xbb, 0xf7, 0xdc, 0x36, 0xe1, 0x76, 0xab, 0x62,
	0xe7, 0x4c, 0xe8, 0xd0, 0xb6, 0xa6, 0xf0, 0x48, 0x75, 0xd8, 0x2b, 0x68, 0x32, 0x71, 0xf3, 0x55,
	0xc5, 0x0e, 0xed, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x63, 0x6c, 0xbb, 0xf5, 0xe3, 0x00, 0x00,
	0x00,
}
